version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: mustafar
      POSTGRES_PASSWORD: 4eki2515
      POSTGRES_DB: ticketa
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - "postgres"
    networks:
      - default
    ports:
      - "8080:8080"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@momoanimation.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  dbdata: # create the volume for persisting data.